// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// import { defineConfig } from "prisma";
// There is no 'defineConfig' export from 'prisma'. Prisma does not require a TypeScript config file like this.
// You can remove this import and the use of defineConfig, or use a plain JS/TS export if needed.
export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
};
// If you need to export a config object, you can do so directly without 'defineConfig'.
